/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dinosauri;

import java.io.IOException;

/**
 *
 * @author bernicchi.davide
 */
public class TavoloDiGioco extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TavoloDiGioco.class.getName());
    private static Tavolo table;
    /**
     * Creates new form TavoloDiGioco
     */
    public TavoloDiGioco() {
        initComponents();
        this.ButtonAddPlr1.setEnabled(true);
        this.ButtonAddPlr2.setEnabled(false);
        this.ButtonAddPlr1.setVisible(true);
        this.ButtonAddPlr2.setVisible(true);
        this.ButtonStart.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonAddPlr1 = new javax.swing.JButton();
        ButtonAddPlr2 = new javax.swing.JButton();
        ButtonStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pannelloTavolo = new javax.swing.JTextArea();
        LableNomeG1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LablePuntiG1 = new javax.swing.JLabel();
        LableNomeG2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LablePuntiG2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ButtonAddPlr1.setText("add giocatore 1");
        ButtonAddPlr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddPlr1ActionPerformed(evt);
            }
        });

        ButtonAddPlr2.setText("add giocatore 2");
        ButtonAddPlr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAddPlr2ActionPerformed(evt);
            }
        });

        ButtonStart.setText("Start");
        ButtonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonStartActionPerformed(evt);
            }
        });

        pannelloTavolo.setColumns(20);
        pannelloTavolo.setRows(5);
        jScrollPane1.setViewportView(pannelloTavolo);

        LableNomeG1.setText("...");

        jLabel2.setText(":");

        LablePuntiG1.setText("...");

        LableNomeG2.setText("...");

        jLabel5.setText(":");

        LablePuntiG2.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonStart)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonAddPlr1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LableNomeG1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LablePuntiG1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonAddPlr2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LableNomeG2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LablePuntiG2)))))
                        .addGap(0, 833, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAddPlr1)
                    .addComponent(ButtonAddPlr2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonStart)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LableNomeG1)
                    .addComponent(jLabel2)
                    .addComponent(LablePuntiG1)
                    .addComponent(LableNomeG2)
                    .addComponent(jLabel5)
                    .addComponent(LablePuntiG2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonAddPlr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddPlr1ActionPerformed
        try {
            table.fillMazzo();
        } catch (IOException ex) {
            System.getLogger(TavoloDiGioco.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        this.LableNomeG1.setText("Gocatore1");
        try {
            // TODO add your handling code here:
            table.addPlayer();
        } catch (IOException ex) {
            System.getLogger(TavoloDiGioco.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
        this.ButtonAddPlr2.setEnabled(true);
        this.ButtonAddPlr1.setEnabled(false);
    }//GEN-LAST:event_ButtonAddPlr1ActionPerformed

    private void ButtonAddPlr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAddPlr2ActionPerformed
        this.LableNomeG2.setText("Gocatore2");
        try {

            table.addPlayer();
        } catch (IOException ex) {
            System.getLogger(dinosauri.TavoloDiGioco.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }   
        this.ButtonAddPlr1.setVisible(false);
        this.ButtonAddPlr2.setVisible(false);
        this.ButtonStart.setVisible(true);
    }//GEN-LAST:event_ButtonAddPlr2ActionPerformed

    private void ButtonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonStartActionPerformed

        table.iniziapartita(pannelloTavolo);
                this.LablePuntiG1.setText("" + table.getPlayer1().getPunti());
        this.LablePuntiG1.setText("" + table.getPlayer2().getPunti());
    }//GEN-LAST:event_ButtonStartActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String[] args) throws IOException {
        
        String file= "mazzo.txt";
        FileManager fm = new FileManager(file);
        table = new Tavolo(fm);
        
        TavoloDiGioco tg = new TavoloDiGioco();
        tg.setVisible(true);
        

        
        tg.setExtendedState(tg.MAXIMIZED_BOTH);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAddPlr1;
    private javax.swing.JButton ButtonAddPlr2;
    private javax.swing.JButton ButtonStart;
    private javax.swing.JLabel LableNomeG1;
    private javax.swing.JLabel LableNomeG2;
    private javax.swing.JLabel LablePuntiG1;
    private javax.swing.JLabel LablePuntiG2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea pannelloTavolo;
    // End of variables declaration//GEN-END:variables
}
